// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw8MH2WPRrNeINI1izqjGifNcxZPURhPA',
    appId: '1:552045119723:web:40443b097f3a2d282596ae',
    messagingSenderId: '552045119723',
    projectId: 'uber-clone-2-8ce6c',
    authDomain: 'uber-clone-2-8ce6c.firebaseapp.com',
    storageBucket: 'uber-clone-2-8ce6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm-9QG9g-6uxZbC_IhxgKzaX6GCOTykAA',
    appId: '1:552045119723:android:de4bcf3792604ccc2596ae',
    messagingSenderId: '552045119723',
    projectId: 'uber-clone-2-8ce6c',
    storageBucket: 'uber-clone-2-8ce6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEiqfGyTYAqqau2vZa-mAGDHmhSWu4X3c',
    appId: '1:552045119723:ios:de95b07f62a587f82596ae',
    messagingSenderId: '552045119723',
    projectId: 'uber-clone-2-8ce6c',
    storageBucket: 'uber-clone-2-8ce6c.appspot.com',
    iosBundleId: 'com.example.uberClone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEiqfGyTYAqqau2vZa-mAGDHmhSWu4X3c',
    appId: '1:552045119723:ios:de95b07f62a587f82596ae',
    messagingSenderId: '552045119723',
    projectId: 'uber-clone-2-8ce6c',
    storageBucket: 'uber-clone-2-8ce6c.appspot.com',
    iosBundleId: 'com.example.uberClone2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw8MH2WPRrNeINI1izqjGifNcxZPURhPA',
    appId: '1:552045119723:web:3b14ae5959a7caa12596ae',
    messagingSenderId: '552045119723',
    projectId: 'uber-clone-2-8ce6c',
    authDomain: 'uber-clone-2-8ce6c.firebaseapp.com',
    storageBucket: 'uber-clone-2-8ce6c.appspot.com',
  );
}
